/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fenster {
    pub title: *const ::core::ffi::c_char,
    pub width: ::core::ffi::c_int,
    pub height: ::core::ffi::c_int,
    pub buf: *mut u32,
    pub keys: [::core::ffi::c_int; 256usize],
    pub mod_: ::core::ffi::c_int,
    pub x: ::core::ffi::c_int,
    pub y: ::core::ffi::c_int,
    pub mouse: ::core::ffi::c_int,
}
unsafe extern "C" {
    pub fn fenster_open(f: *mut fenster) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fenster_loop(f: *mut fenster) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn fenster_close(f: *mut fenster);
}
unsafe extern "C" {
    pub fn fenster_sleep(ms: i64);
}
unsafe extern "C" {
    pub fn fenster_time() -> i64;
}
unsafe extern "C" {
    pub fn fenster_create(
        title: *const ::core::ffi::c_char,
        width: ::core::ffi::c_int,
        height: ::core::ffi::c_int,
        buf: *mut u32,
    ) -> *mut fenster;
}
unsafe extern "C" {
    pub fn fenster_destroy(f: *mut *mut fenster);
}
